/**
 * Created with JetBrains WebStorm.
 * User: yj
 * Date: 16-10-22
 * Time: 下午2:48
 * To change this template use File | Settings | File Templates.
 */
lbt.service("DeepIntoComputerData",[function(){
    return {
        "name": "穿越计算机的迷雾",
        "chapters": [{
            "name":"电流和电压",
            "content":{
                "dirName": "DeepIntoComputer",
                "noteList":[{
                    "title": "电流和电压的产生原理",
                    "items": [{
                        showStyle: "txt",
                        specContent: "电池的作用就像内部安了一个电泵，它促使整个线路中的电子像水流一样不停地循环流动。当\"电泵\"开始工作时，它的任务是从电线一边的原子那里夺走自由电子，并将它们送给电线另一边的原子。这样，失去电子的原子很着急，而得到电子的原子也不会因为自己的电子多了而高兴，它们都急切地想要找回电子或者扔掉包袱而重新达到稳定状态。在这种情况下，电压产生了。"
                    }]
                },{
					"title": "电压的本质",
					"items": [{
						showStyle:"txt",
						specContent:"电压是一种吸引力，是由于失去电子和希望重新得到电子而引起的。电压的存在是导致电流产生的原因"
					}]
				}]
            }
        },{
            "name":"电磁学",
            "content":{
                "dirName": "DeepIntoComputer",
                "noteList":[{
                    "title":"继电器",
                    "items":[{
                        "showStyle":"txt",
                        "specContent":"继电器的符号表示"
                    },{
                        "showStyle":"img",
                        "specContent":"relay-sign.png"
                    },{
                        "showStyle":"txt",
                        "specContent":"图中的方框代表电磁铁，而在右边，紧挨着它的是一个衔铁开关。同时，图中也表明了继电器实际上可以按工作状态分为两种：左边那种平时处于断开状态，只有在电磁铁加电的时候才吸合接通；右边那种相反"
                    }]
                },{
                    "title":"无线电产生实验",
                    "items":[{
                        "showStyle":"txt",
                        "specContent":"当电磁铁断电的一瞬间，绕在它上面的线圈产生了非常高的电压。在电磁学中，这叫做自感。自感能产生瞬时高压，可以发生在线圈通电或断电的一瞬间。可以理解为：当线圈通电或断电时，它的磁场会急剧发生变化，从而在自身产生感应电压。通常，影响自感强烈程度的因素包括线圈的匝数、形状，以及绕在哪种类型的铁芯上。"
                    },{
                        "showStyle":"txt",
                        "specContent":"自感能产生瞬时高压，可以发生在线圈通电或断电的一瞬间。可以理解为：当线圈通电或断电时，它的磁场会急剧发生变化，从而在自身产生感应电压。通常，影响自感强烈程度的因素包括线圈的匝数、形状，以及绕在哪种类型的铁芯上。"
                    },{
                        "showStyle":"txt",
                        "specContent":"从严格的电磁学来说，产生自感的原因是在开关闭合或者断开的瞬间，电流大小急剧变化，从而产生了一个同样迅速变化的磁场，这个磁场反过来在同一个线圈中产生电磁感应。"
                    },{
                        "showStyle":"txt",
                        "specContent":"自感可以用来产生电磁波"
                    },{
                        "showStyle":"img",
                        "specContent":"self-induction-experiment.png"
                    },{
                        "showStyle":"txt",
                        "specContent":"开关K和线圈L2以及电源构成一个串联的通路。这样，当整个电路接通的时候，由于K是闭合的，铁框会产生磁性，从而把K吸开，电路断开。电路一断开，K又恢复原状，电路又被接通，循环往复。"
                    },{
                        "showStyle":"txt",
                        "specContent":"自感持续发生时，整个铁框中的磁场也在跟着变化，这是一个比较强的磁场。铁框另一边，线圈L1的两端分别连接着铜球Q1和Q2。由于L1的匝数是L2的几百倍，属于升压变压器，当L2上的自感持续发生的时候，根据变压器的原理，这会在L1上产生几万伏的高压，使得距离很近的Q1和Q2产生持续的放电，Q1和Q2之间就会出现电火花。"
                    },{
                        "showStyle":"txt",
                        "specContent":"产生火花是因为高压的存在，有一部分空气被击穿（在高压的作用下，空气分子被迫变成导体，这时空气已经被击穿）而放电。在这个过程中，参与导电的空气分子越来越多，电流越来越大，而且很不规则。同时，这些空气分子急剧升温，并引起空气扰动，这就是火花和响声的来源。之后，电流逐渐变小，最后火花消失，响声也没有了，电流变为0，整个过程只是一瞬间"
                    }]
                }]
            }
        },{
            "name":"逻辑电路",
            "content":{
                "dirName":"DeepIntoComputer",
                "noteList":[{
                    "title":"非门",
                    "items":[{
                        "showStyle":"txt",
                        "specContent":"非门的电路实现"
                    },{
                        "showStyle":"img",
                        "specContent":"not-gate.png"
                    },{
                        "showStyle":"txt",
                        "specContent":"由于我们不可能为每个门电路装上一节电池，因此，它内部的每个部分都用同一个电源供电，如下图所示"
                    },{
                        "showStyle":"img",
                        "specContent":"one-power-supply-not-gate.png"
                    },{
                        "showStyle":"txt",
                        "specContent":"我们采用接地线的方式改造上面的电路"
                    },{
                        "showStyle":"img",
                        "specContent":"earth-wire-not-gate.png"
                    },{
                        "showStyle":"txt",
                        "specContent":"更专业一点的画法，电源不必画出来，只用一些符号，例如Vcc只电源正极，表示那根电线要接到电源正极，而电路中所有的地线都应当汇集起来连接到电源负极"
                    },{
                        "showStyle":"img",
                        "specContent":"simple-not-gate.png"
                    },{
                        "showStyle":"txt",
                        "specContent":"正式的非门表示方法"
                    },{
                        "showStyle":"img",
                        "specContent":"formal-not-gate.png"
                    }]
                },{
                    "title":"与门",
                    "items":[{
                        "showStyle":"txt",
                        "specContent":"根据上面非门的推导，很容易得到与门的表示"
                    },{
                        "showStyle":"img",
                        "specContent":"and-gate.png"
                    }]
                },{
                    "title":"或门",
                    "items":[{
                        "showStyle":"txt",
                        "specContent":"或门主要用到了并联开关"
                    },{
                        "showStyle":"img",
                        "specContent":"or-gate.png"
                    }]
                },{
                    "title":"异或门",
                    "items":[{
                        "showStyle":"img",
                        "specContent":"and-or-gate-expression.png"
                    },{
                        "showStyle":"img",
                        "specContent":"and-or-gate.png"
                    },{
                        "showStyle":"img",
                        "specContent":"and-or-gate-actual.png"
                    }]
                }]
            }
        },{
            "name":"加法机",
            "content":{
                "dirName": "DeepIntoComputer",
                "noteList":[{
                    "title": "加法机引入",
                    "items": [{
                        showStyle: "txt",
                        specContent: "考虑上进位的情况，二进制数的相加总共有8种情况"
                    },{
                        showStyle: "img",
                        specContent: "binary-addition.png"
                    },{
                        showStyle: "txt",
                        specContent: "全加器的构造如下"
                    },{
                        showStyle:"img",
                        specContent:"full-adder-structrue.png"
                    },{
                        showStyle:"txt",
                        specContent:"在图中，A和B分别是来自被加数和加数的一个比特，他们正好在同一列上；Ci是来自右边一列的进位；Co是本列产生的进位；S是本列的“和”。"
                    },{
                        showStyle:"img",
                        specContent:"3-bit-adder.png"
                    }]
                },{
                    "title":"加法机内部结构及其原理",
                    "items":[{
                        showStyle:"txt",
                        specContent:"全加器输出端S的真值表"
                    },{
                        showStyle:"img",
                        specContent:"output-terminal.png"
                    },{
                        showStyle:"txt",
                        specContent:"全加器进位Co的真值表"
                    },{
                        showStyle:"img",
                        specContent:"adder-carry.png"
                    },{
                        showStyle:"txt",
                        specContent:"从上面的真值表中我们可以得到输出端和进位的逻辑表达式"
                    },{
                        showStyle:"img",
                        specContent:"output-terminal-logic-expression.png"
                    },{
                        showStyle:"img",
                        specContent:"adder-carry-logic-expression.png"
                    },{
                        showStyle:"txt",
                        specContent:"全加器内部构造细节"
                    },{
                        showStyle:"img",
                        specContent:"adder-inner-structure.png"
                    },{
                        showStyle:"txt",
                        specContent:"上面的全加器输出和进位的逻辑表达式经过简化之后可以化简为"
                    },{
                        showStyle:"img",
                        specContent:"simplified-adder-expression.png"
                    },{
                        showStyle:"img",
                        specContent:"simplified-adder.png"
                    }]
                },{
                    "title":"加法机的组成",
                    "items":[{
                        showStyle:"txt",
                        specContent:"当把所有的加法器连接在一起、封装在一起的时候，我们就会看到一个完整的加法机"
                    },{
                        showStyle:"img",
                        specContent:"complete-adder.png"
                    }]
                }]
            }
        },{
            "name":"触发器",
            "content":{
                "dirName":"DeepIntoComputer",
                "noteList":[{
                    "title": "反馈和振荡器",
                    "items":[{
                        showStyle:"txt",
                        specContent:"回顾一下非门"
                    },{
                        showStyle:"img",
                        specContent:"not-gate-review.png"
                    },{
                        showStyle:"txt",
                        specContent:"我们把它的输入连同那个开关统统去掉，直接用它的输出作为输入，如下图"
                    },{
                        showStyle:"img",
                        specContent:"feedback-not-gate.png"
                    },{
                        showStyle:"txt",
                        specContent:"由于继电器衔铁平时是闭合的，当它一通电，会立即使灯泡点亮。不过，这个输入有是继电器的输入，所以在灯泡亮的同时，电磁铁产生磁力，马上又把衔铁开关拉开，于是，灯又灭了。同时电磁铁同时也失去磁性，于是衔铁开关又恢复原状，将电路接通，灯又亮了。所以这只灯泡将一亮一灭的进行下去。"
                    },{
                        showStyle:"txt",
                        specContent:"把一个非门的输出取出一部分来，同时又作为它的输入，这样就形成了一个反馈。"
                    },{
                        showStyle:"txt",
                        specContent:"一个非门，再加上反馈之后，就能产生一连串交替变化的输出，使得与之相连的灯泡一亮一灭，这种东西在电子技术领域叫做振荡器。"
                    }]
                },{
                    "title":"电子管时代",
                    "items":[{
                        showStyle:"txt",
                        specContent:"发明振荡器，最早的目的是为了向天空中扬撒电磁波。在20世纪之前人们就知道，要想产生电磁波，必须使电流以极高的速度不断变化，而要产生高速变化的电流，振荡器可以做到这一点。"
                    },{
                        showStyle:"txt",
                        specContent:"电磁波的发现使科学家们非常激动，因为他们很想借助它来传递声音，这样就不需要架设电线了，会节省很大的成本。愿望是好的，但在当时不可能实现，原因有两条：第一，没有一种好的方法把来自话筒的声音电流加载到电磁波上，而且在接收方，也没办法将微弱的信号放大。第二，当时的电磁波发生装置都很原始，电流通过空气放电时，是一个没有规律的导电过程。这意味着，不规则的急速变化的电流，将产生包含各种频率成分的电磁波，这种电磁波是不纯净的。我们需要的是那种波形非常规则，并且只在单一频率上工作的发射装置。那么我们刚刚发明的振荡器不就很好吗？而且当时已经有了继电器。答案是不可以，因为发射电磁波需要很高的振荡频率，而继电器显然不能胜任。我们平时用收音机听的广播，它的频率在500-1600kHz之间；电视节目则需要几百兆赫兹的频率，而手机则更高，为几个吉赫兹。继电器是机械装置每秒蹦跶几下、十几下还行，要是让它每秒钟蹦跶几百万下，太难为它了。所以，要发明一样东西，可能需要事先发明另外一些东西。"
                    }]
                },{
                    "title":"电子二极管",
                    "items":[{
                        showStyle:"txt",
                        specContent:"1904年11月16日，一个名叫弗莱明的英国人发明了一种新鲜玩意儿。在一个被抽成真空的灯泡内安两根导线，其中一根安装在离灯丝不远的地方，隔着一定的距离，再安装上另一根导线，如下图所示"
                    },{
                        showStyle:"img",
                        specContent:"diode.png"
                    },{
                        showStyle:"txt",
                        specContent:"接下来组装如下电路"
                    },{
                        showStyle:"img",
                        specContent:"diode-circuit.png"
                    },{
                        showStyle:"txt",
                        specContent:"通常，右边那只灯泡是不会亮的。但是，不要这么肯定，我们就是因为喜欢想当然的下结论，才经常犯错误，实际上只要给灯丝通上电，让它灼热发光，这回，在真空中两个隔着一定距离的导线居然有电流通过，右边那只灯泡居然亮了。而且，如果将电源正负极对调，电流就消失了。"
                    },{
                        showStyle:"txt",
                        specContent:"这事儿肯定和灼热的灯丝有关，因为只有在它通电烧热的时候才会发生这样的情况，但不一定是非常直接的关系。毕竟，在灯丝和接电源负极的那根导线之间还有一点点距离。也就是说，电子不是从灯丝那里来的。当时，具体的原因弗莱明也不清楚。现在我们知道，要是在两根金属之间加上电压，被灯丝烤得灼热的金属可以在真空里发射电子。这个装置具有单向导电性，它就是电子二极管。靠近灯丝的那块金属叫阴极，因为它通常要接在电源的负极上，主要作用是发射电子；另一块金属叫做阳极，通常接在电源的正极上，用来把电子从阴极吸引过去。还有两个引脚是给灯丝供电的，不是真正对我们有用的那一部分。如下图所示，那是它的专用符号。注意那个图，阴极被画成一个半圆。这不是为了显得美观而特意这样画的，而是当人们了解了电子二极管的工作原理之后，为了使阴极能更有效的被灯丝加热，把它做成了一个筒形。而且在这个小筒的底部，涂了一层氧化物，这是因为氧化物在加热之后，发射电子的本领更高。"
                    },{
                        showStyle:"img",
                        specContent:"diode-sketch-map.png"
                    },{
                        showStyle:"txt",
                        specContent:"那个时代是电学大发展的前夜，人们乐于尝试，其中有一个叫福雷斯特的美国人干的最为起劲。他希望能为二极管做一些完善的工作。很自然的，人们会想到，既然电子是从阴极通过真空流向阳极，那么能不能控制它的流量，同时，也许能够看到一些古怪的事情发生。为了控制电子从阴极到阳极之间的流动，他在原有的电子二极管里，也就是阴极和阳极之间，又加了一根金属丝，后来改成了金属网。之所以做成网状，是因为既能够让电子们容易通过，又可以对它们加以控制，因此称之为控制栅极，也叫栅极。如下图所示"
                    },{
                        showStyle:"img",
                        specContent:"controll-diode.png"
                    },{
                        showStyle:"txt",
                        specContent:"在这个装置上，他给阴极和阳极供电，就像电子二极管那样。同时也给栅极供电，如下图。"
                    },{
                        showStyle:"img",
                        specContent:"controll-diode-circuit.png"
                    },{
                        showStyle:"txt",
                        specContent:"和他预料的一样，福雷斯特发现，通过改变栅极上电压的大小和极性，可以改变阳极上电流的强弱，甚至切断它，这叫做截止。这似乎没有什么新意。但是，令人意想不到的是，只要栅极上的电流发生一点点变化，阳极上的电流就会大幅度地跟着改变。例如上图，细微调整栅极电源，就会明显地改变灯泡的亮度。这意味着，电子三极管有放大作用。这在电学史上是个很重要的事件。需要注意的是，电子三极管的放大效果不是无端凭空产生的，这个放大后的能量来自于电源，它只是一个转换器。福雷斯特发明的电子三极管很快风靡世界。首先，贝尔和爱迪生他们肯定非常喜欢，因为他们正在为电话的信号太弱而发愁，有了电子三极管，无论多么微弱的声音信号，都可以变得十分洪亮。除了有线的东西需要电子管，无线的东西也搭上了顺风车。利用它的放大作用，再加上适当的反馈，就可以形成一个振荡器能够产生固定频率的振荡电流。如果它的振荡频率足够高，就能向很远的地方发射无线电波，而且它的优势是可以获得极高的振荡频率，因为电子管的开关速度很快。"
                    }]
                },{
                    "title":"触发器",
                    "items":[{
                        showStyle:"txt",
                        specContent:"当时，研究如何用电磁波来进行通信的人很多。在这些专家李，有一个叫埃克尔斯和一个叫乔丹的英国人，他们两个的工作内容是研究无线电波的发射和接收。要发射电磁波，就要有振荡器。长久以来，制造振荡器的方法就是在电路中加入反馈，就像我们刚刚用非门制造的那个振荡器一样。1918年，这两位一起发明了一种具有记忆功能的电路。这个电路的核心是两个电子三极管，之所以让人觉得新奇，是因为它能记住你刚才对它做了什么手脚。这个电路上下对称，分别都是一个活门连着一个非门，特别之处在于，它们各自的输出又分别作为对方的输入。换句话说，在这个电路里存在两个反馈。如下图所示："
                    },{
                        showStyle:"img",
                        specContent:"trigger.png"
                    },{
                        showStyle:"txt",
                        specContent:"接下来，我们逐步研究这个电路的原理"
                    },{
                        showStyle:"img",
                        specContent:"trigger-principle.png"
                    },{
                        showStyle:"txt",
                        specContent:"电路刚接好的时候，你要确保两个开关都是断开的。现在，我们合上开关R，如下图："
                    },{
                        showStyle:"img",
                        specContent:"trigger-principle-1.png"
                    },{
                        showStyle:"txt",
                        specContent:"闭合R就等于R=1，于是不管Q以前是亮还是灭，它现在一定不会发光，即Q=0。然后，因为有反馈的存在，Q=0紧接着被送到下面。同时，因为S也是0，所以经或门和非门后，灯泡Q'接通，变亮，即Q'=1。当然Q'=1又被反馈到上面。但是，因为R已经给或门提供了“1”，所以Q的状态不会受到影响，整个电路就此处于稳定状态不再改变。此时，即使断开R，灯泡Q依然不亮，而灯泡Q'依然亮着！不管怎么合上或关闭R，Q和Q'还是那样。"
                    },{
                        showStyle:"txt",
                        specContent:"由于电路对称，上下两部分一模一样，所以当我们让R一直处于断开状态，将S合上。灯泡Q亮着，而Q'却不亮了！"
                    },{
                        showStyle:"txt",
                        specContent:"上面的这个装置就是触发器。触发器的工作状态依赖于两个开关S和R，闭合一个断开另一个，总是会得到两个相反的输出Q和Q'；要是这两个开关都断开，那么取决于Q和Q'刚才处于什么状态，它们依然保持这种状态不变。这些都是我们知道的。还有最后一种状态，要是S和R都闭合，会怎样呢？如下图所示："
                    },{
                        showStyle:"img",
                        specContent:"trigger-principle-2.png"
                    },{
                        showStyle:"txt",
                        specContent:"通常情况下，灯泡Q和Q'是互补的，一个亮起来，另一个就会熄灭，能自己达到合适的稳定状态。但是现在，虽然电路里依然存在反馈，但是不起作用，整个电路现在已经丧失了记忆力，已经失去理智、精神错乱了。两个灯泡都不会亮。"
                    },{
                        showStyle:"txt",
                        specContent:"总结一下，这里讲的触发器，一共有4种工作状态："
                    },{
                        showStyle:"img",
                        specContent:"trigger-work-state.png"
                    },{
                        showStyle:"txt",
                        specContent:"现在再来想一个问题，当这个电路刚刚通电时（R和S都是断开的），两个灯泡是什么状态？"
                    },{
                        showStyle:"txt",
                        specContent:"答案是不知道，不一定。因为这里面存在反馈，会引发竞争，竞争的结果是肯定有一个灯亮，而另一个不亮。但是到底哪个亮，哪个不亮，这个无法事先知晓，既然是竞争，那么竞争的结果只有咋实际开始竞争以后才知道。竞争结果取决于双方实力，在这个电路里，就是零件的参数和工作速度，速度慢的一方只能在竞争中处于下风。"
                    },{
                        showStyle:"txt",
                        specContent:"触发器的符号"
                    },{
                        showStyle:"img",
                        specContent:"R-S-trigger.png"
                    },{
                        showStyle:"txt",
                        specContent:"这是最早的，也是最基本的一种触发器，我们一般称之为R-S触发器。触发器有两个截然相反的输出，多数情况下我们只需要一个输出就已足够。因此，一直以来就把Q作为触发器的输出。结合触发器真值表可以看出，在触发器正常工作的前提下，Q的输出和S的输入总是一致的，S=0则Q=0；S=1则Q=1。这意味着可以通过设置S的值，使得Q的输出和S保持一致，这就是“S”的由来。不管Q以前是什么，比如Q0，我们可以通过让S=1来使Q变成1。但是，当R=1的话，Q又变回0，这等于将Q打回原形，这称为“恢复”或者“复位”，这就是“R”的由来。"
                    }]
                }]
            }
        },{
            "name":"跑马灯",
            "content":{
                "dirName":"DeepIntoComputer",
                "noteList":[{
                    "title":"能保存一个比特的触发器",
                    "items":[{
                        showStyle:"txt",
                        specContent:"触发器的特点是当它触发的时候，输出会发生变化。但是当输入撤销之后，输出依然能够维持。也就是说，触发器具有记忆能力。我们希望用触发器保存一个比特，一个比特只需要一根电线就可以传送，但是触发器要正常工作，要想使Q=0，则S必须为0，R必须为1；要想使Q=1，必须使S=1而R=0。此时，我们可以拿一个非门来实现："
                    },{
                        showStyle:"img",
                        specContent:"1-bit-trigger.png"
                    },{
                        showStyle:"txt",
                        specContent:"如下图所示，电路刚接好的时候，开关是断开的。断开的时候相当于要保存一个比特“0”。这时，S=0，R=1，Q=0，灯不会亮"
                    },{
                        showStyle:"txt",
                        specContent:"接下来，用手摁一下开关，电路被接通，相当于输入为“1”。这时，S=1，R=0，触发器保存这个比特，于是灯亮了"
                    },{
                        showStyle:"img",
                        specContent:"1-bit-trigger-circuit.png"
                    },{
                        showStyle:"txt",
                        specContent:"接下来，关键来了，我们一撒手，开关自动弹起来，如果灯泡依然亮着才表名我们的触发器可以保存并维持一个比特，但是事与愿违，小灯泡不亮。"
                    },{
                        showStyle:"txt",
                        specContent:"原因也很简单，开关弹开，相当于输入的比特是“0”，于是S=0，R=1，Q=0，灯泡自然不亮。"
                    },{
                        showStyle:"txt",
                        specContent:"为了解决上述问题，我们需要将上述电路稍加改造，给触发器一个控制端CP，如下图所示："
                    },{
                        showStyle:"img",
                        specContent:"control-terminal-trigger.png"
                    },{
                        showStyle:"txt",
                        specContent:"通常情况下，CP=0，意思是现在不想保存数据。这时，因为与门的关系，不管D上是什么，S和R都为0，所以触发器保持原有的内容不变。也就是说CP=0的另一层意思是期望触发器不被外面的数据干扰，继续保持原先保存的那个比特。在触发器前面放两个与门，不单单是保护原有的比特，它们还有更重要的任务。比如，如果D=0，而且CP=1的时候，S=0而R=1，于是“0”就会被保存到触发器里（Q=0）。同样是CP=1，要是D=1，那么S=1而R=0，于是“1”就被保存到触发器里（Q=1），不管保存的是“0”还是“1”，当它成功进入触发器之后，CP就会变成0，于是S和R会一直为0。这种触发器叫做D触发器。如下图所示："
                    },{
                        showStyle:"img",
                        specContent:"d-trigger.png"
                    }]
                },{
                    "title":"边沿触发",
                    "items":[{
                        showStyle:"txt",
                        specContent:"控制端CP通常都是带有有效期的，它的有效期就是CP=1的时间。当CP=1时，在它的持续期间，D触发器会工作，随时都会因为外来的比特变了而触发；一旦CP=0，就意味着过了有效期，触发器将不能保存新的比特。例如下面的例子："
                    },{
                        showStyle:"img",
                        specContent:"trigger-question-1.png"
                    },{
                        showStyle:"txt",
                        specContent:"上图中，从t0时刻开始，D和CP各自出现了上图所示的脉冲，那么在t1时刻，触发器里保存的是多少呢？实际上我们只需要分析在CP=1的期间，只要D端比特变了，触发器就会随时出发。所以，在CP最后从1变成0的时候D端的比特是0，因此Q端输出是0，伺候CP变成0，D端不论怎么变化Q端的值都不会变，因此在t1时刻Q端的值是0。"
                    },{
                        showStyle:"txt",
                        specContent:"现在，我们需要一种新的触发器，该触发器要在CP为1或为0的期间不触发，只在CP从低到高，或者从高到底变化的瞬间触发。而从0到1，或从1到0，这个变化过程称为“跳变”或者“翻转”。CP的跳变需要一个过程，这个过程非常短暂。反应在图像上，就是两个边沿，一个上升沿，一个下降沿。因此，我们即将发明的这个触发器就叫边沿触发器，具体还可以分为上升沿D触发器和下降沿D触发器，目前我们只介绍上升沿D触发器。如下图所示："
                    },{
                        showStyle:"img",
                        specContent:"rising-edge-trigger.png"
                    },{
                        showStyle:"txt",
                        specContent:"这个大触发器由两个小触发器首尾相连而构成，前一个触发器的输出是后一个触发器的输入，而且这两个触发器永远不会同时工作，因为控制脉冲是右边那个触发器的直接领导，而想要给左边的触发器下达命令必须通过一个非门。"
                    },{
                        showStyle:"txt",
                        specContent:"如果想在这个电路里保存一个比特，必须先使控制端为0。此时，左边的触发器CP=1，它可以保存任何要保存的比特，并将该比特传输给右侧的触发器。但是，右侧的触发器不工作。现在，如果控制端从0跳变到1，说时迟，那时快，一切都颠倒了，左边的触发器不再保存任何比特，右边的触发器开始工作，把左边那个触发器的输出保存起来。直到这个时候，比特才算是被这个大触发器保存了。此后，如果控制端从1又回到0，即下降沿，左边的触发器才开始工作，但右边的触发器却停止工作，但它仍然有能力维持原先的输出不变。也就是说，控制脉冲的下降沿不会改变这个大触发器的内容。通常用下面的图来表示上升沿触发器："
                    },{
                        showStyle:"img",
                        specContent:"rising-edge-trigger-sign.png"
                    },{
                        showStyle:"txt",
                        specContent:"此时，思考一个问题，在上面思考题的那张图中，同样是在t1时刻，上升沿触发器D里保存的是什么？由于上升沿触发器只在上升沿触发，因此，CP在由0变为1的瞬间，D的值为1，此后到t1之前CP再也没有出现过上升沿，因此在t1时刻上升沿触发器D的输出为1。"
                    }]
                },{
                    "title":"走马灯之谜",
                    "items":[{
                        showStyle:"txt",
                        specContent:"回顾上升沿触发器：只在CP脉冲的上升沿触发，比特从输入端输入后，经过一个小小的延迟，才能稳定的出现在输出端Q上。延迟的事件或长或短，取决于制造一个触发器所使用的材料。如果用的是继电器，这个延迟会以秒为单位，大约是零点几秒到1秒钟，因为它不单纯是电子的，更是机械的；如果你用的是电子管或者更好的材料，这个延迟可以缩短到几个纳秒。基于这一点，我们可以把若干上升沿D触发器首尾相连，并把它们的CP端连在一起，让它们可以在同一时间触发，如下图所示："
                    },{
                        showStyle:"img",
                        specContent:"many-rising-edge-trigger.png"
                    },{
                        showStyle:"txt",
                        specContent:"如图所示，我们想办法让最左边的触发器保存比特“1”，其他的触发器都保存比特“0”。通常情况下，按键开关是断开的，所有触发器都不工作，因为它们的CP都为0.一旦开关按下，在电路接通的瞬间，所有的触发器都会看到一个上升沿，于是它们的第一反应是将前一个触发器的输出保存起来。一个小小的延迟之后，它们接收到的比特会出现在各自的输出端Q上。但是由于上升沿已经过去，它们只好就此停下来。不过此时，第一个触发器的Q已经不再为1，取而代之的是第二个触发器。也就是说，如果不停的按动开关，这个比特1就会在触发器间顺序地传递，从左向右，最后再回到左边，这样循环往复。现在，我们要是每个触发器在把输出送往下一个触发器的同时，还连一个灯泡，这就是我们想要的走马灯。再用一个非门振荡器来代替不断需要用手摁的开关。"
                    },{
                        showStyle:"img",
                        specContent:"merry-go-round.png"
                    },{
                        showStyle:"txt",
                        specContent:"这个走马灯速度是可调的，如果振荡器振荡频率很高的话，灯泡亮灭之间的变换就会很快，反之则慢。"
                    },{
                        showStyle:"txt",
                        specContent:"不把振荡器和灯泡算在内，一个走马灯电路通常称为循环移位寄存器。所谓“寄存”的意思是临时存放。当若干个触发器组合在一起，可以同时保存许多比特时，就称为寄存器。"
                    },{
                        showStyle:"txt",
                        specContent:"循环移位寄存器只是移位寄存器里面的一种。移位寄存器可以用来保存多个比特，并将这些比特顺序左移或者右移。我们知道，当用加法机做加法时，加数和被加数的所有比特都是同时进入加法机的，这称为“并行”。但是在另一些场合，为了迁就也有的电路和设施，二进制数需要按顺序拆开，然后一个比特一个比特地分别传输，到达目的地后再按原来的次序组装起来，这称为“串行”。典型的例子就是通过电话线上网，或者往U盘里复制资料，这些情况下，所有信息都是通过电话线或者数据线一个比特一个比特传送的。"
                    }]
                },{
                    "title":"乒乓触发器",
                    "items":[{
                        showStyle:"img",
                        specContent:"ping-pong-trigger.png"
                    },{
                        showStyle:"txt",
                        specContent:"这个触发器的输出Q非又被送入输入端D，看起来像是一个反馈。为了弄清楚它的工作原理，我们需要开关和灯泡这两个工具。开关用于生成控制脉冲，而灯泡则可以使我们观察到开关对灯泡的亮灭会产生什么影响。"
                    },{
                        showStyle:"img",
                        specContent:"ping-pong-trigger-circuit.png"
                    },{
                        showStyle:"txt",
                        specContent:"假设Q=1而Q非为0，灯泡是亮的。只要开关是断开的，CP端就看不到上升沿，触发器也不会工作，所以从Q非到D上的反馈在触发器内部被阻断。如果按下开关，在它的上升沿，触发器动作，将D上的比特0。结果可以预料到，那就是导致Q和Q非同时翻转，Q=0而Q非=1，灯泡熄灭。"
                    },{
                        showStyle:"txt",
                        specContent:"我们知道，触发器更像是一根管道，D上的比特被保存之后需要经历一个小小的延迟，才会使Q和Q非产生变化。实际上，当Q和Q非翻转之后，CP的上升沿已经过去，在下一个上升沿到来之前，从Q非到D上的反馈又一次被阻断。同理可以分析，在又一次按下开关之后，Q=1而Q非=0，灯泡又亮了。换句话说，它就是一个乒乓开关，或者叫反复开关，教授们通常叫T触发器，T是toggle的意思。"
                    }]
                }]
            }
        },{
            "name":"电子管到晶体管",
            "content":{
                "dirName":"DeepIntoComputer",
                "noteList":[{
                    title:"纯电子化的计算机时代",
                    items:[{
                        showStyle:"txt",
                        specContent:"用继电器制造的运算电路是一个名副其实的怪胎，因为它的工作需要电流的驱动，但它的吸合和释放却是一个机械过程。也就是说，它一半是机械的，一半是电子的。除此之外，它的工作速度也不太令人满意，因为它的触发过程不会在瞬间完成。"
                    },{
                        showStyle:"txt",
                        specContent:"计算机应当摆脱机械，包括笨拙的继电器，完全实现纯电子化的运算，纯电子化的运算很奇妙，两股代表着不同数值的电流在某个装置内汇合，互相影响，变成另一股合适的电流，这就是计算结果。最重要的是，在这个过程中没有机械的影子，看不到继电器衔铁的西河与释放，也听不到已经司空见惯的噼啪声。第一个作出这项变革的，是一个叫约翰 文森特 阿塔纳索夫的人。"
                    },{
                        showStyle:"txt",
                        specContent:"1937年冬天，阿塔纳索夫找到了使计算机实现纯电子化运算的答案。他的核心思想是使用二进制，并采用电子管来制作进行加减乘除所需要的逻辑电路。电子管是新材料，继电器能做的事情，它也能做。比如，可以利用电子三极管的栅极来控制阴极和阳极之间的通断，这就相当于一个逻辑上的非门。电子管还有一些继电器所不具备的优势，它是纯电子的，开关速度要比继电器快成千上万倍。但遗憾的是，电子管的结构比灯泡复杂了很多，价格自然也很贵。更重要的是，尽管那个时候电子管无疑是最好的材料，但计算机自己的理论准备却刚刚开始。所以，电子管的兴旺和计算机没关系。计算机一直在按自己的步调慢慢发展，但在这个过程中，另一种比电子管更好的东西出现了——晶体管"
                    }]
                },{
                    title:"晶体管",
                    items:[{
                        showStyle:"txt",
                        specContent:"撇开制造计算机不论，即使对于其他行业来说，使用电子管也有一些不便之处。电子管体积太大，数量一多就占地方。还有，工作之前要靠灯丝把阴极烧热。而成千上万的电子管的灯丝统统烧热，不知道要花多少钱。而且从灯丝发热到把阴极烤得能发射电子还需要一段时间，称为预热。最后，这东西怕振，振的厉害就容易散架。于是，科学家们就忙着搞新的发明，准备革电子管的命。最终，这好事摊到了一个叫肖克利的人头上。"
                    },{
                        showStyle:"txt",
                        specContent:"晶体管是电子管更好的替代品，被称为20世纪最重要的发明。我们这里要讨论两种叫硅和锗的晶体。硅和锗的导电性能介于导体和绝缘体之间，因此，又叫半导体。"
                    },{
                        showStyle:"txt",
                        specContent:"拿一块纯净的本征半导体，在一边掺上硼，另一边掺上磷，然后分别引出两根导线。这样做了之后，不但这块半导体的导电性获得了很大改善，而且像电子二极管一样，具有单向导电性。"
                    },{
                        showStyle:"img",
                        specContent:"crystal-diode.png"
                    },{
                        showStyle:"txt",
                        specContent:"发光二极管的体积小，不需要高热的灯丝就能发光。更重要的是，它耗电量非常小。晶体二极管只具备单向导电性，不具备放大作用。不过，在接着摸索了一段时间之后，这也不再是一团迷雾。如下图，在一块本征半导体的两边掺上硼，在中间掺上磷（中间这个区域一般做得很薄，大约有1微米到十几微米，而且掺的很少），这样就发明了一种新型的半导体材料。"
                    },{
                        showStyle:"img",
                        specContent:"crystal-triode.png"
                    },{
                        showStyle:"txt",
                        specContent:"此时，只要电流I1发生一点点变化，电流I2就会大幅度跟着变化。这就是晶体三极管。"
                    },{
                        showStyle:"txt",
                        specContent:"不像电子管，晶体管可以做得很小、很轻巧，不需要很高电压就能工作，更不需要一个灯丝来为它加热。"
                    }]
                },{
                    title:"计数器",
                    items:[{
                        showStyle:"txt",
                        specContent:"为了方便起见，将乒乓触发器表示如下："
                    },{
                        showStyle:"img",
                        specContent:"ping-pong-trigger-sign.png"
                    },{
                        showStyle:"txt",
                        specContent:"下图所示的计数器用了5个乒乓触发器。很明显，从每个触发器的输出端Q非都连着下一个触发器的控制端CP。在这个计数器开始工作之前，需要将每个触发器清零，使Q4Q3Q2Q1Q0=00000，这表示的是1个二进制数，也就是十进制的0.毫无疑问，所有触发器的输出端Q非也都为1。在第一个时钟脉冲到来的时候，在它的上升沿，最右边的那个触发器FF0翻转，使得它的输出Q=1，于是Q4Q3Q2Q1Q0=00001，即十进制的1。与此同时，Q非也从以前的1翻转到了0。但由于它处于下降沿，因此不会对FF1及其他任何触发器造成影响。同理，当第二个脉冲到来的时候，FF0的Q从原来的1变成0，即Q0=0，Q非从0变为1。对于FF1来说，FF0的Q非从0变成1就意味着它的CP看到了一个上升沿，所以它也紧跟着触发，使得Q1=1。同时，FF1的Q非也从1翻转到了0，但这是一个下降沿，所以其他触发器不会跟着变化。此时，Q4Q3Q2Q1Q0=00010，即十进制的2，按照同样的思路分析，当第三个脉冲到来时，为00011，第四个脉冲到来时为00100。"
                    },{
                        showStyle:"img",
                        specContent:"counter.png"
                    }]
                }]
            }
        },{
            "name":"用机器做一连串加法",
            "content":{
                "dirName":"DeepIntoComputer",
                "noteList":[{
                    title:"把一大堆数加起来",
                    items:[{
                        showStyle:""
                    }]
                }]
            }
        }]
    };
}]);